name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Format code with Black
        run: black .

      #- name: Lint code with flake8
        #run: |
          #pip install flake8
          #flake8 . 

  test:
    runs-on: ubuntu-latest
    needs: lint  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      # For develop branch, just run tests without Kafka
      - name: Run unit and integration tests without kafka broker
        if: github.ref == 'refs/heads/develop'  # Only run this for the develop branch
        run: |
          pip install pytest pytest-asyncio
          pytest tests/test_pipeline.py  

      # Conditional step for Kafka (only for the main branch)
      - name: Start Kafka and Zookeeper with Docker Compose
        if: github.ref == 'refs/heads/main'  # Only run this for the main branch
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose -f docker-compose.yml up -d
          docker-compose ps  # Ensure services are up

      - name: Run all tests in test_pipeline.py (Main Branch)
        if: github.ref == 'refs/heads/main'  # Only run this for the main branch
        run: |
          pip install pytest pytest-asyncio  # Install pytest and pytest-asyncio for async tests
          pytest tests/test_pipeline.py --maxfail=1 --disable-warnings -q  # Run all tests in test_pipeline.py

      # Conditional shutdown for Kafka and Zookeeper (only for the main branch)
      - name: Shutdown Kafka and Zookeeper after tests
        if: github.ref == 'refs/heads/main'  # Only run this for the main branch
        run: |
          docker-compose down  # Stop and remove containers

      # For main branch, just run tests with Kafka
      - name: Run unit and integration tests rely on kafka broker
        if: github.ref == 'refs/heads/main'  # Only run this for the main branch
        run: |
          pip install pytest pytest-asyncio
          pytest tests/  
